#!/bin/sh

RPI=root@RPI1.localdomain
TA=8aaaf200-2450-11e4-abe2-0002a5d5c51e.ta

ssh ${RPI} 'mkdir -p mock-ta'
ssh ${RPI} 'mkdir -p fake-ta'

scp run-test ${RPI}:
scp build/rpi4/test-app ${RPI}:
scp build/rpi4/mock-ta/${TA} ${RPI}:mock-ta/
scp build/rpi4/fake-ta/${TA} ${RPI}:fake-ta/
