#!/bin/sh

# adjust paths
OPTEEOS_DIR=/d1/optee/optee-qemu/optee_os
OPTEECLIENT_DIR=/d1/optee/optee-qemu/optee_client
CC=/opt/toolchain/gcc-arm-10.3-2021.07-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-

mkdir -p build/qemu

# test-app
${CC}c++ test-app.cpp \
  -I${OPTEECLIENT_DIR} \
  -L${OPTEECLIENT_DIR} \
  -lteec \
  -o build/qemu/test-app

# mock-ta
make \
  CROSS_COMPILE=${CC} \
  TA_DEV_KIT_DIR=${OPTEEOS_DIR}/export-ta_arm32 \
  O=build/qemu/mock-ta

# fake-ta
make \
  CROSS_COMPILE=${CC} \
  TA_DEV_KIT_DIR=${OPTEEOS_DIR}/export-ta_arm32 \
  TA_SIGN_KEY=rsa2048.pem \
  O=build/qemu/fake-ta
