#!/bin/sh

# adjust paths
OPTEEOS_DIR=/d1/optee/optee_os-rpi4
OPTEECLIENT_DIR=/d1/buildroot/build/linux-rpi/build/optee-client-3.18.0
CC=/opt/toolchain/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-

mkdir -p build/rpi4

# test-app
${CC}c++ test-app.cpp \
  -I${OPTEECLIENT_DIR}/public \
  -L${OPTEECLIENT_DIR}/libteec \
  -lteec \
  -o build/rpi4/test-app

# mock-ta
make \
  CROSS_COMPILE64=${CC} \
  TA_DEV_KIT_DIR=${OPTEEOS_DIR}/out/arm-plat-rpi4/export-ta_arm64 \
  O=build/rpi4/mock-ta

# fake-ta
make \
  CROSS_COMPILE64=${CC} \
  TA_DEV_KIT_DIR=${OPTEEOS_DIR}/out/arm-plat-rpi4/export-ta_arm64 \
  TA_SIGN_KEY=rsa2048.pem \
  O=build/rpi4/fake-ta

cd ..
