#!/bin/sh

make \
  CROSS_COMPILE=/opt/toolchain/gcc-arm-10.3-2021.07-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf- \
  TA_DEV_KIT_DIR=/d1/optee/optee-qemu/optee_os/export-ta_arm32 \
  O=build
